import { Employee } from '../types';

// Helper to parse date from M/D/YYYY to YYYY-MM-DD
const parseDate = (str: string): string => {
  const parts = str.split('/');
  if (parts.length !== 3) return str;
  let month = parseInt(parts[0], 10);
  let day = parseInt(parts[1], 10);
  const year = parseInt(parts[2], 10);

  // Sanity check: if month > 12 and day <= 12, swap them (assuming D/M/Y was intended)
  if (month > 12 && day <= 12) {
    const temp = month;
    month = day;
    day = temp;
  }

  const monthStr = month.toString().padStart(2, '0');
  const dayStr = day.toString().padStart(2, '0');

  return `${year}-${monthStr}-${dayStr}`;
};

const rawData = [
  { name: 'Alina Miller', dob: '6/20/2002', start: '5/9/2025', prev: 0, vr: 'VR1' },
  { name: 'Anna Kvitová', dob: '8/9/1995', start: '6/1/2024', prev: 0, vr: 'VR2' },
  { name: 'Anthony Allen', dob: '1/16/1990', start: '5/27/2024', prev: 0, vr: 'VR2' },
  { name: 'Ari Karl', dob: '4/14/2005', start: '4/30/2025', prev: 0, vr: 'VR1' },
  { name: 'Ben Massey', dob: '4/9/1999', start: '10/29/2024', prev: 0, vr: 'VR2' },
  { name: 'Bríet Valdís Reeve', dob: '7/23/2008', start: '12/27/2024', prev: 0, vr: 'VR1' },
  { name: 'Cale Galbraith', dob: '6/26/2001', start: '9/18/2023', prev: 0, vr: 'VR2' },
  { name: 'Chantel Jones', dob: '7/13/1996', start: '2/27/2025', prev: 0, vr: 'VR1' },
  { name: 'Elijah Owens', dob: '2/25/1997', start: '7/25/2023', prev: 0, vr: 'VR2' },
  { name: 'Elisa Nina', dob: '12/25/2002', start: '9/2/2023', prev: 0, vr: 'VR2' },
  { name: 'Elvar Gapunay', dob: '8/24/2001', start: '10/1/2024', prev: 0, vr: 'VR2' },
  { name: 'Emil Baldursson', dob: '9/4/1998', start: '5/20/2025', prev: 0, vr: 'VR1' },
  { name: 'Emilía Áróra', dob: '6/4/2007', start: '6/25/2025', prev: 0, vr: 'VR0' },
  { name: 'Enrique Morales', dob: '12/1/1995', start: '1/7/2024', prev: 0, vr: 'VR2' },
  { name: 'Fabien Dambron', dob: '5/15/1985', start: '6/7/2024', prev: 0, vr: 'VR2' },
  { name: 'Gareth Wild', dob: '5/8/1986', start: '9/8/2025', prev: 24, vr: 'VR2' },
  { name: 'Gloriousgospel Henry', dob: '10/18/2000', start: '4/29/2025', prev: 0, vr: 'VR1' },
  { name: 'Iva Vladimirová', dob: '4/30/1998', start: '1/25/2024', prev: 0, vr: 'VR2' },
  { name: 'Jack Bandak', dob: '11/24/2002', start: '2/28/2025', prev: 0, vr: 'VR1' },
  { name: 'Jarred Stancil', dob: '6/13/1994', start: '4/25/2025', prev: 24, vr: 'VR2' },
  { name: 'Jasmín Luana', dob: '9/7/2002', start: '4/26/2025', prev: 0, vr: 'VR1' },
  { name: 'Laura Petrone', dob: '12/20/1996', start: '12/16/2024', prev: 0, vr: 'VR1' },
  { name: 'Lucia Lara', dob: '6/5/2000', start: '5/5/2025', prev: 0, vr: 'VR1' },
  { name: 'Luz Medina', dob: '4/27/1996', start: '6/15/2023', prev: 0, vr: 'VR2' },
  { name: 'Marieta Zderic', dob: '9/4/1999', start: '10/1/2024', prev: 0, vr: 'VR2' },
  { name: 'Michael Hansen', dob: '12/31/1987', start: '10/1/2024', prev: 0, vr: 'VR2' },
  { name: 'Paola Tunarosa', dob: '3/27/2003', start: '5/16/2025', prev: 0, vr: 'VR1' },
  { name: 'Rachel Ogimont', dob: '8/9/2001', start: '6/28/2025', prev: 0, vr: 'VR1' },
  { name: 'Robin Schindfessel', dob: '3/10/2001', start: '1/20/2025', prev: 0, vr: 'VR1' },
  { name: 'Roksana Owczarek', dob: '9/2/2003', start: '6/20/2023', prev: 0, vr: 'VR2' },
  { name: 'Sophie Pietrzok', dob: '7/11/2000', start: '6/12/2023', prev: 0, vr: 'VR2' },
  { name: 'Tiana Dusil', dob: '9/4/1999', start: '9/4/2025', prev: 0, vr: 'VR1' },
  { name: 'Zachary Owens', dob: '6/3/1996', start: '11/2/2024', prev: 0, vr: 'VR2' },
];

export const INITIAL_EMPLOYEES: Employee[] = rawData.map((data) => {
  const parts = data.name.split(' ');
  const lastName = parts.pop() || '';
  const firstName = parts.join(' ');

  return {
    id: '00000000-0000-0000-0000-000000000000', // Placeholder UUID, will be ignored/regenerated by DB
    firstName,
    lastName,
    dateOfBirth: parseDate(data.dob),
    startDate: parseDate(data.start),
    previousExperienceMonths: data.prev,
    statusVR: data.vr,
    gender: 'Other', // Placeholder as requested
    country: 'Unknown', // Placeholder as requested
    role: 'Employee',
    languages: [],
    sickDaysYTD: 0,
    performanceRating: 3,
    totalExperienceMonths: 0, // Calculated field, will be updated by enrichEmployee
    monthsToNextRaise: null,
    customFields: {},
  };
});
