import { Employee } from '../types';

export const seedEmployees: Employee[] = [
  {
    id: 'alma-miller',
    firstName: 'Alma',
    lastName: 'Miller',
    gender: 'Female',
    country: 'USA',
    role: 'Analyst',
    statusVR: 'VR2',
    dateOfBirth: '2002-06-26',
    startDate: '2023-05-09',
    previousExperienceMonths: 0,
    totalExperienceMonths: 31,
    monthsToNextRaise: 1,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 331,
      experienceMonths: 0,
      targetVrRate: 'VR3',
      monthsAtCurrentRate: 4.5,
    },
  },
  {
    id: 'amira-kotlov',
    firstName: 'Amira',
    lastName: 'Kotlov',
    gender: 'Female',
    country: 'USA',
    role: 'Associate',
    statusVR: 'VR0',
    dateOfBirth: '1999-04-08',
    startDate: '2024-01-13',
    previousExperienceMonths: 0,
    totalExperienceMonths: 8,
    monthsToNextRaise: 1,
    sickDaysYTD: 0,
    performanceRating: 3,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 137,
      experienceMonths: 0,
      targetVrRate: 'VR1',
      monthsAtCurrentRate: 4.5,
    },
  },
  {
    id: 'anthony-allen',
    firstName: 'Anthony',
    lastName: 'Allen',
    gender: 'Male',
    country: 'USA',
    role: 'Manager',
    statusVR: 'VR3',
    dateOfBirth: '1990-01-16',
    startDate: '2022-05-27',
    previousExperienceMonths: 12,
    totalExperienceMonths: 44,
    monthsToNextRaise: 7,
    sickDaysYTD: 1,
    performanceRating: 5,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 391,
      experienceMonths: 12,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'ben-mason',
    firstName: 'Ben',
    lastName: 'Mason',
    gender: 'Male',
    country: 'USA',
    role: 'Senior Engineer',
    statusVR: 'VR4',
    dateOfBirth: '1983-07-02',
    startDate: '2020-04-06',
    previousExperienceMonths: 48,
    totalExperienceMonths: 86,
    monthsToNextRaise: 4,
    sickDaysYTD: 0,
    performanceRating: 5,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 1066,
      experienceMonths: 48,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'betti-wadey-reese',
    firstName: 'Betti',
    lastName: 'Wadey Reese',
    gender: 'Female',
    country: 'USA',
    role: 'Coordinator',
    statusVR: 'VR2',
    dateOfBirth: '1999-06-14',
    startDate: '2022-03-01',
    previousExperienceMonths: 0,
    totalExperienceMonths: 51,
    monthsToNextRaise: 0,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 443,
      experienceMonths: 0,
      targetVrRate: 'VR3',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'caleb-jordan',
    firstName: 'Caleb',
    lastName: 'Jordan',
    gender: 'Male',
    country: 'USA',
    role: 'Engineer',
    statusVR: 'VR2',
    dateOfBirth: '2001-12-26',
    startDate: '2022-09-02',
    previousExperienceMonths: 0,
    totalExperienceMonths: 30,
    monthsToNextRaise: 0,
    sickDaysYTD: 0,
    performanceRating: 3,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 625,
      experienceMonths: 0,
      targetVrRate: 'VR3',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'chatan-jones',
    firstName: 'Chatan',
    lastName: 'Jones',
    gender: 'Male',
    country: 'USA',
    role: 'Intern',
    statusVR: 'VR0',
    dateOfBirth: '2006-08-03',
    startDate: '2024-04-29',
    previousExperienceMonths: 0,
    totalExperienceMonths: 5,
    monthsToNextRaise: 1,
    sickDaysYTD: 0,
    performanceRating: 3,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 129,
      experienceMonths: 0,
      targetVrRate: 'VR1',
      monthsAtCurrentRate: 4.5,
    },
  },
  {
    id: 'elsa-gonzalez',
    firstName: 'Elsa',
    lastName: 'Gonzalez',
    gender: 'Female',
    country: 'USA',
    role: 'Analyst',
    statusVR: 'VR2',
    dateOfBirth: '2003-08-18',
    startDate: '2023-09-05',
    previousExperienceMonths: 0,
    totalExperienceMonths: 19,
    monthsToNextRaise: 6,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English', 'Spanish'],
    customFields: {
      totalDaysWorked: 341,
      experienceMonths: 0,
      targetVrRate: 'VR3',
      monthsAtCurrentRate: 4.5,
    },
  },
  {
    id: 'elsa-graham',
    firstName: 'Elsa',
    lastName: 'Graham',
    gender: 'Female',
    country: 'USA',
    role: 'Senior Analyst',
    statusVR: 'VR3',
    dateOfBirth: '2001-09-24',
    startDate: '2020-09-22',
    previousExperienceMonths: 12,
    totalExperienceMonths: 74,
    monthsToNextRaise: 11,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 558,
      experienceMonths: 12,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'emil-baldursson',
    firstName: 'Emil',
    lastName: 'Baldursson',
    gender: 'Male',
    country: 'Iceland',
    role: 'Engineer',
    statusVR: 'VR1',
    dateOfBirth: '1998-09-04',
    startDate: '2023-05-20',
    previousExperienceMonths: 0,
    totalExperienceMonths: 23,
    monthsToNextRaise: 4,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['Icelandic', 'English'],
    customFields: {
      totalDaysWorked: 319,
      experienceMonths: 0,
      targetVrRate: 'VR2',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'emilia-ariza',
    firstName: 'Emilia',
    lastName: 'Ariza',
    gender: 'Female',
    country: 'USA',
    role: 'Engineer',
    statusVR: 'VR3',
    dateOfBirth: '2002-01-03',
    startDate: '2020-09-10',
    previousExperienceMonths: 0,
    totalExperienceMonths: 76,
    monthsToNextRaise: 5,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English', 'Spanish'],
    customFields: {
      totalDaysWorked: 666,
      experienceMonths: 0,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'ethan-kelly',
    firstName: 'Ethan',
    lastName: 'Kelly',
    gender: 'Male',
    country: 'USA',
    role: 'Senior Engineer',
    statusVR: 'VR3',
    dateOfBirth: '1988-10-07',
    startDate: '2020-05-04',
    previousExperienceMonths: 0,
    totalExperienceMonths: 73,
    monthsToNextRaise: 8,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 778,
      experienceMonths: 0,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 7,
    },
  },
  {
    id: 'fabian-johnson',
    firstName: 'Fabian',
    lastName: 'Johnson',
    gender: 'Male',
    country: 'USA',
    role: 'Engineer',
    statusVR: 'VR3',
    dateOfBirth: '1995-10-23',
    startDate: '2021-05-22',
    previousExperienceMonths: 36,
    totalExperienceMonths: 78,
    monthsToNextRaise: 15,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 462,
      experienceMonths: 36,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 7,
    },
  },
  {
    id: 'gabriela-jordan',
    firstName: 'Gabriela',
    lastName: 'Jordan',
    gender: 'Female',
    country: 'USA',
    role: 'Analyst',
    statusVR: 'VR2',
    dateOfBirth: '2000-02-16',
    startDate: '2023-12-08',
    previousExperienceMonths: 12,
    totalExperienceMonths: 41,
    monthsToNextRaise: 4,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English', 'Spanish'],
    customFields: {
      totalDaysWorked: 262,
      experienceMonths: 12,
      targetVrRate: 'VR3',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'giuseppe-vivaldi',
    firstName: 'Giuseppe',
    lastName: 'Vivaldi',
    gender: 'Male',
    country: 'Italy',
    role: 'Director',
    statusVR: 'VR4',
    dateOfBirth: '1978-04-24',
    startDate: '2019-10-24',
    previousExperienceMonths: 0,
    totalExperienceMonths: 65,
    monthsToNextRaise: 15,
    sickDaysYTD: 0,
    performanceRating: 5,
    languages: ['Italian', 'English'],
    customFields: {
      totalDaysWorked: 866,
      experienceMonths: 0,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 7,
    },
  },
  {
    id: 'jack-standel',
    firstName: 'Jack',
    lastName: 'Standel',
    gender: 'Male',
    country: 'USA',
    role: 'Engineer',
    statusVR: 'VR3',
    dateOfBirth: '1997-11-16',
    startDate: '2022-03-03',
    previousExperienceMonths: 0,
    totalExperienceMonths: 44,
    monthsToNextRaise: 2,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 583,
      experienceMonths: 0,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 4.5,
    },
  },
  {
    id: 'james-kaba',
    firstName: 'James',
    lastName: 'Kaba',
    gender: 'Male',
    country: 'USA',
    role: 'Analyst',
    statusVR: 'VR3',
    dateOfBirth: '1994-04-12',
    startDate: '2021-02-17',
    previousExperienceMonths: 0,
    totalExperienceMonths: 52,
    monthsToNextRaise: 0,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 641,
      experienceMonths: 0,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'jasira-hendrix',
    firstName: 'Jasira',
    lastName: 'Hendrix',
    gender: 'Female',
    country: 'USA',
    role: 'Engineer',
    statusVR: 'VR2',
    dateOfBirth: '2002-09-29',
    startDate: '2022-08-30',
    previousExperienceMonths: 0,
    totalExperienceMonths: 38,
    monthsToNextRaise: 6,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 649,
      experienceMonths: 0,
      targetVrRate: 'VR3',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'javier-gonzales',
    firstName: 'Javier',
    lastName: 'Gonzales',
    gender: 'Male',
    country: 'USA',
    role: 'Engineer',
    statusVR: 'VR2',
    dateOfBirth: '2001-10-20',
    startDate: '2022-09-27',
    previousExperienceMonths: 0,
    totalExperienceMonths: 37,
    monthsToNextRaise: 1,
    sickDaysYTD: 0,
    performanceRating: 3,
    languages: ['English', 'Spanish'],
    customFields: {
      totalDaysWorked: 638,
      experienceMonths: 0,
      targetVrRate: 'VR3',
      monthsAtCurrentRate: 7,
    },
  },
  {
    id: 'jenna-liljestrand',
    firstName: 'Jenna',
    lastName: 'Liljestrand',
    gender: 'Female',
    country: 'USA',
    role: 'Lead Engineer',
    statusVR: 'VR4',
    dateOfBirth: '1991-02-09',
    startDate: '2022-03-29',
    previousExperienceMonths: 72,
    totalExperienceMonths: 107,
    monthsToNextRaise: 14,
    sickDaysYTD: 0,
    performanceRating: 5,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 415,
      experienceMonths: 72,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'jenna-lopez',
    firstName: 'Jenna',
    lastName: 'Lopez',
    gender: 'Female',
    country: 'USA',
    role: 'Associate',
    statusVR: 'VR0',
    dateOfBirth: '2002-02-04',
    startDate: '2024-03-14',
    previousExperienceMonths: 0,
    totalExperienceMonths: 8,
    monthsToNextRaise: 6,
    sickDaysYTD: 0,
    performanceRating: 3,
    languages: ['English', 'Spanish'],
    customFields: {
      totalDaysWorked: 150,
      experienceMonths: 0,
      targetVrRate: 'VR1',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'kale-leeds',
    firstName: 'Kale',
    lastName: 'Leeds',
    gender: 'Male',
    country: 'USA',
    role: 'Engineer',
    statusVR: 'VR2',
    dateOfBirth: '2000-12-02',
    startDate: '2023-08-04',
    previousExperienceMonths: 0,
    totalExperienceMonths: 22,
    monthsToNextRaise: 0,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 374,
      experienceMonths: 0,
      targetVrRate: 'VR3',
      monthsAtCurrentRate: 7,
    },
  },
  {
    id: 'maddie-keller',
    firstName: 'Maddie',
    lastName: 'Keller',
    gender: 'Female',
    country: 'USA',
    role: 'Engineer',
    statusVR: 'VR1',
    dateOfBirth: '1993-10-13',
    startDate: '2024-04-12',
    previousExperienceMonths: 12,
    totalExperienceMonths: 19,
    monthsToNextRaise: 5,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 151,
      experienceMonths: 12,
      targetVrRate: 'VR2',
      monthsAtCurrentRate: 7,
    },
  },
  {
    id: 'may-lazo',
    firstName: 'May',
    lastName: 'Lazo',
    gender: 'Female',
    country: 'USA',
    role: 'Manager',
    statusVR: 'VR4',
    dateOfBirth: '1985-02-09',
    startDate: '2020-06-04',
    previousExperienceMonths: 0,
    totalExperienceMonths: 76,
    monthsToNextRaise: 5,
    sickDaysYTD: 0,
    performanceRating: 5,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 948,
      experienceMonths: 0,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'melanie-podolak',
    firstName: 'Melanie',
    lastName: 'Podolak',
    gender: 'Female',
    country: 'USA',
    role: 'Analyst',
    statusVR: 'VR2',
    dateOfBirth: '2001-08-24',
    startDate: '2023-09-25',
    previousExperienceMonths: 0,
    totalExperienceMonths: 18,
    monthsToNextRaise: 5,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 333,
      experienceMonths: 0,
      targetVrRate: 'VR3',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'nicolette-carls',
    firstName: 'Nicolette',
    lastName: 'Carls',
    gender: 'Female',
    country: 'USA',
    role: 'Coordinator',
    statusVR: 'VR0',
    dateOfBirth: '1997-01-11',
    startDate: '2024-01-29',
    previousExperienceMonths: 0,
    totalExperienceMonths: 8,
    monthsToNextRaise: 2,
    sickDaysYTD: 0,
    performanceRating: 3,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 112,
      experienceMonths: 0,
      targetVrRate: 'VR1',
      monthsAtCurrentRate: 7,
    },
  },
  {
    id: 'rachel-piruzza',
    firstName: 'Rachel',
    lastName: 'Piruzza',
    gender: 'Female',
    country: 'USA',
    role: 'Analyst',
    statusVR: 'VR1',
    dateOfBirth: '2003-12-15',
    startDate: '2022-03-10',
    previousExperienceMonths: 0,
    totalExperienceMonths: 27,
    monthsToNextRaise: 6,
    sickDaysYTD: 0,
    performanceRating: 3,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 593,
      experienceMonths: 0,
      targetVrRate: 'VR2',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'sam-lopez',
    firstName: 'Sam',
    lastName: 'Lopez',
    gender: 'Male',
    country: 'USA',
    role: 'Senior Analyst',
    statusVR: 'VR4',
    dateOfBirth: '2001-11-10',
    startDate: '2019-06-03',
    previousExperienceMonths: 18,
    totalExperienceMonths: 64,
    monthsToNextRaise: 0,
    sickDaysYTD: 0,
    performanceRating: 4,
    languages: ['English', 'Spanish'],
    customFields: {
      totalDaysWorked: 373,
      experienceMonths: 18,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 6,
    },
  },
  {
    id: 'zachary-owens',
    firstName: 'Zachary',
    lastName: 'Owens',
    gender: 'Male',
    country: 'USA',
    role: 'Architect',
    statusVR: 'VR4',
    dateOfBirth: '1995-02-18',
    startDate: '2023-06-16',
    previousExperienceMonths: 48,
    totalExperienceMonths: 99,
    monthsToNextRaise: 6,
    sickDaysYTD: 0,
    performanceRating: 5,
    languages: ['English'],
    customFields: {
      totalDaysWorked: 454,
      experienceMonths: 48,
      targetVrRate: 'VR4',
      monthsAtCurrentRate: 6,
    },
  },
];
